# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linkmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
